apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: simple-serving-ocha-demo-scale
  namespace: serving-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/metric: "rps"
      name: simple-serving-ocha-demo-scale-v3
    spec:
      containers:
      - image: nrt.ocir.io/orasejapan/ocha-demo-sonk8s-serving:v3
        ports:
        - containerPort: 8080
