apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: keda-demo
data:
  sasl: cGxhaW50ZXh0Cg==
  tls: ZW5hYmxlCg==
  username: <ユーザ名>
  password: <認証トークン>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: keda-demo
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: password
  - parameter: tls
    name: keda-kafka-secrets
    key: tls