apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-demo-deploy
  namespace: keda-demo
  labels:
    app: keda-demo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-demo-deploy
  template:
    metadata:
      labels:
        app: keda-demo-deploy
    spec:
      containers:
      - name: keda-demo-deploy
        image: <コンテナイメージパス>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080